name: Build

on:
  workflow_dispatch:
  push:
    # only run for branches, not tags
    branches: ['**']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{matrix.node}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm run test
