# Copyright 2023 Rob Spoor
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: SonarCloud

on:
  workflow_dispatch:
  push:
    # only run for branches, not tags
    branches: ['**']
  pull_request:
  schedule:
    - cron: '0 6 5 3,9 *'

jobs:
  scan:
    runs-on: ubuntu-latest
    concurrency: sonar-${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Create Sonar properties
        run: |
          echo "sonar.organization=robtimus-github" > sonar-project.properties
          echo "sonar.projectKey=robtimus:`jq -r .name package.json`" >> sonar-project.properties
          echo "sonar.projectDescription=`jq -r .description package.json`" >> sonar-project.properties
          echo "sonar.links.homepage=`jq -r .homepage package.json`" >> sonar-project.properties
          echo "sonar.links.issue=`jq -r .bugs.url package.json`" >> sonar-project.properties
          echo "sonar.links.scm=`jq -r .repository.url package.json | sed 's/git+//'`" >> sonar-project.properties
          echo "sonar.sources=src" >> sonar-project.properties
          echo "sonar.tests=test" >> sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=./coverage/lcov.info" >> sonar-project.properties
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SonarCloudToken }}
          SONAR_HOST_URL: https://sonarcloud.io
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SonarCloudToken }}
          SONAR_HOST_URL: https://sonarcloud.io
